from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from trace_collect.restore_cost_analysis import (
    analyze_restore_cost_sweep,
    render_summary_markdown,
    run_mode_b_refit,
)
from trace_collect.tool_latency_offline_probe import evaluate_offline_probe_clock


def test_restore_cost_sweep_rescoring_matches_hand_computed_deltas(
    tmp_path: Path,
) -> None:
    _write_confirmation_cv(
        tmp_path,
        {
            "f1": [_decision("a", "task-a", latency_ms=80.0)],
            "f2": [_decision("b", "task-b", latency_ms=150.0)],
        },
    )

    result = analyze_restore_cost_sweep(
        tmp_path,
        restore_cost_fractions=[0.0, 0.5],
        replicates=100,
        confidence_level=0.95,
        seed=0,
    )

    assert result["fold_names"] == ["f1", "f2"]
    assert result["decision_row_count"] == 2
    assert result["costs_ms"] == [100.0]
    totals = {
        name: {
            fraction: payload["points"]["100.0"]["paired_delta_ms"]
            for fraction, payload in comparison["by_restore_cost_fraction"].items()
        }
        for name, comparison in result["comparisons"].items()
    }
    # task-a: robust fires at 0 on a short call (-20 - 100f), gated waits (0);
    # task-b: robust fires at 0 on a long call (+100), gated equals deadline.
    assert totals["gated_vs_robust"] == {"0.0": -80.0, "0.5": -30.0}
    assert totals["gated_vs_deadline"] == {"0.0": 0.0, "0.5": 0.0}
    assert totals["robust_vs_deadline"] == {"0.0": 80.0, "0.5": 30.0}

    summary = render_summary_markdown(result)
    assert "## gated_vs_robust" in summary
    assert "| 0.5 |" in summary


def test_restore_cost_sweep_rejects_conflicting_fold_stamp(tmp_path: Path) -> None:
    row = _decision("a", "task-a", latency_ms=80.0)
    row["outer_fold"] = "f9"
    _write_confirmation_cv(tmp_path, {"f1": [row]})

    with pytest.raises(ValueError, match="conflicts with fold file"):
        analyze_restore_cost_sweep(
            tmp_path,
            restore_cost_fractions=[0.0],
            replicates=100,
            confidence_level=0.95,
            seed=0,
        )


def test_restore_cost_sweep_rejects_duplicate_fractions(tmp_path: Path) -> None:
    _write_confirmation_cv(
        tmp_path,
        {"f1": [_decision("a", "task-a", latency_ms=80.0)]},
    )

    with pytest.raises(ValueError, match="unique"):
        analyze_restore_cost_sweep(
            tmp_path,
            restore_cost_fractions=[0.5, 0.5],
            replicates=100,
            confidence_level=0.95,
            seed=0,
        )


def test_mode_b_refit_reproduces_frozen_zero_and_adapts_triggers(
    tmp_path: Path,
) -> None:
    config = {
        "fold_count": 2,
        "inner_folds": 2,
        "costs_ms": [100.0],
        "guard_ms": 0.0,
        "min_tool_history": 1,
        "min_profile_tasks": 1,
        "command_field": None,
        "max_prefix_depth": 4,
        "skip_leading_cd": False,
    }
    tasks = {f"task-{index}": [80.0, 80.0, 150.0] for index in range(8)}
    first_half = {f"task-{index}" for index in range(4)}
    second_half = set(tasks) - first_half
    folds = {"f1": (first_half, second_half), "f2": (second_half, first_half)}
    root = tmp_path / "confirmation"
    (root / "provenance").mkdir(parents=True)
    (root / "provenance" / "manifest.json").write_text(
        json.dumps(config), encoding="utf-8"
    )
    (root / "data").mkdir()
    (root / "cv").mkdir()
    for fold, (eval_tasks, profile_tasks) in folds.items():
        eval_rows = _latency_rows(tasks, eval_tasks)
        profile_rows = _latency_rows(tasks, profile_tasks)
        for name, rows in (("eval", eval_rows), ("profile", profile_rows)):
            (root / "data" / f"{fold}_{name}.jsonl").write_text(
                "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows),
                encoding="utf-8",
            )
        # The "frozen" fixture is generated by the same evaluator, so the
        # fraction-zero check below proves default-vs-explicit-0.0 equality
        # here; cross-version drift is what it guards on real artifacts.
        frozen = evaluate_offline_probe_clock(
            eval_rows,
            profile_rows=profile_rows,
            kv_costs_ms=config["costs_ms"],
            guard_ms=config["guard_ms"],
            inner_folds=config["inner_folds"],
        )
        (root / "cv" / f"{fold}_decisions.jsonl").write_text(
            "".join(
                json.dumps(row, sort_keys=True) + "\n" for row in frozen["decisions"]
            ),
            encoding="utf-8",
        )

    result = run_mode_b_refit(
        root,
        output_root=tmp_path / "mode-b",
        restore_cost_fractions=[0.0, 0.35],
        replicates=100,
        confidence_level=0.95,
        seed=0,
    )

    assert result["frozen_zero_fraction_check"] == "passed"
    refit_rows = [
        json.loads(line)
        for fold in folds
        for line in (tmp_path / "mode-b" / "rho_0.35" / f"{fold}_decisions.jsonl")
        .read_text(encoding="utf-8")
        .splitlines()
    ]
    # At restore 35 every [80,80,150] node prefers k=80 to k=0, so the refit
    # waits past the short calls instead of firing at zero.
    assert {row["offline_gated_robust_trigger_ms"] for row in refit_rows} == {80.0}
    zero_delta = result["comparisons"]["gated_vs_deadline"][
        "by_restore_cost_fraction"
    ]["0.0"]["points"]["100.0"]["paired_delta_ms"]
    refit_delta = result["comparisons"]["gated_vs_deadline"][
        "by_restore_cost_fraction"
    ]["0.35"]["points"]["100.0"]["paired_delta_ms"]
    # rho=0 fires at 0 on every call: each of the 8 long calls hides the full
    # cost (+100 over the deadline's 0) and each of the 16 shorts is exposed
    # for 20; the refit at 0.35 fires at 80 on long calls only (+40 each).
    assert zero_delta == pytest.approx(8 * 100.0 - 16 * 20.0)
    assert refit_delta == pytest.approx(8 * 40.0)


def _latency_rows(
    tasks: dict[str, list[float]],
    task_ids: set[str],
) -> list[dict[str, Any]]:
    return [
        {
            "sample_id": f"{task_id}-{index}",
            "source_trace": f"trace-{task_id}",
            "task_id": task_id,
            "tool_name": "exec",
            "tool_ts_start": 0.0,
            "tool_ts_end": latency_ms / 1000.0,
            "latency_ms": latency_ms,
        }
        for task_id in sorted(task_ids)
        for index, latency_ms in enumerate(tasks[task_id])
    ]


def _decision(
    sample_id: str,
    task_id: str,
    *,
    latency_ms: float,
    cost_ms: float = 100.0,
) -> dict[str, Any]:
    return {
        "sample_id": sample_id,
        "task_id": task_id,
        "latency_ms": latency_ms,
        "kv_cost_ms": cost_ms,
        "threshold_ms": cost_ms,
        "deadline_trigger_ms": cost_ms,
        "robust_trigger_ms": 0.0,
        "offline_gated_robust_trigger_ms": cost_ms,
    }


def _write_confirmation_cv(
    root: Path,
    rows_by_fold: dict[str, list[dict[str, Any]]],
) -> None:
    cv_root = root / "cv"
    cv_root.mkdir(parents=True)
    for fold, rows in rows_by_fold.items():
        (cv_root / f"{fold}_decisions.jsonl").write_text(
            "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows),
            encoding="utf-8",
        )
